#!/usr/bin/env python3
"""Schema compiler: pupyarrow writes the reference messages and locates
the patch slots in its own bytes. Zero dependencies (numpy only).
pyarrow's role is confined to the test suite: it must read everything
the C executor emits from these templates."""
import sys

from quiver.pupyarrow import fb
from quiver.pupyarrow.writer import batch_message, schema_message
from quiver.opcodes import OPCODES

SCHEMAS = {
    "COMP": ([("user_data","u64"),("res","i32"),("read_size","i64"),
              ("cksum","u64"),("etag","large_binary"),("parts","i32")],
             [[1,2],[0,-5],[10,20],[3,4],[b"aa",b"bb"],[0,2]]),
    # zscan member metadata → the planner (replaces a bespoke 36B record)
    # buf_span (trailing): zstream emits each member's total buffer span
    # (bytes since the previous member, absorbing intervening dir/PAX/GNU
    # blocks) so the planner computes exact in_off; zscan emits the tar
    # footprint (zexec ignores it) — a harmless extra column for that path.
    "ZMETA": ([("path","large_string"),("source_id","i32"),("ordinal","i32"),
               ("size","i64"),("mode","i32"),("mtime_ns","i64"),
               ("uid","i32"),("gid","i32"),("buf_span","i64")],
              [["a","bb"],[1,2],[3,4],[5,6],[7,8],[9,10],[11,12],[13,14],[15,16]]),
    # child_count: -1 on a normal stat row; >=0 marks a directory
    # close-event (path=dir, is_dir=1) carrying its emitted-child count,
    # emitted at getdents-EOF only when the scan is asked for closes.
    # bvm's STAT stream (SCAN_FS / SCAN_NAMES / OPEN_TAR -> planner). SUPERSET of
    # qvm's STAT (= pwalk2/ducl's Feather schema: the inode graph + full timestamps)
    # plus blocks' own columns — so ducl can consume bvm scans directly. `link` is ""
    # for plain files, the target for symlinks, the canonical path for hardlinks
    # (kind rides in in_off: 0=symlink, 1=hardlink); OPEN_TAR uses in_off as the
    # member's offset in its frame. Fields a mode doesn't know (names-only scan,
    # tar without inode data) are zero. Replaces a hand-rolled row encoding that
    # Python re-parsed per row (~17x slower than native Arrow).
    "BSTAT": ([("path","large_string"),("link","large_string"),("in_off","i64"),
               ("size","i64"),("blocks","i64"),
               ("mtime_ns","i64"),("atime_ns","i64"),("ctime_ns","i64"),
               ("ino","u64"),("parent_ino","u64"),("dev","u64"),
               ("mode","i32"),("uid","i32"),("gid","i32"),("nlink","i32"),
               ("depth","i32"),("is_dir","u8"),
               ("digest","i64"),("chunks","large_binary")],
              # digest: whole-file BLAKE2b-64 (-1 = absent). chunks: FastCDC manifest
              # [u32 n][n x (u32 len, u64 hi, u64 lo)] — 128-bit two-seed chunk ids,
              # empty for files < 128K (they ARE their single chunk). APPENDED so all
              # existing BSTAT buffer indexes (0-35) stay stable.
              [["a","bb"],["c","dd"]] + [[1,2]]*6 + [[3,4]]*3 + [[5,6]]*5
              + [[0,1]] + [[7,8]] + [[b"x",b"yy"]]),
    "STAT": ([("path","large_string"),("size","i64"),("blocks","i64"),
              ("mtime_ns","i64"),("atime_ns","i64"),("ctime_ns","i64"),
              ("ino","u64"),("parent_ino","u64"),("dev","u64"),
              ("mode","i32"),("uid","i32"),("gid","i32"),("nlink","i32"),
              ("depth","i32"),("is_dir","u8"),("child_count","i64")],
             [["a","bb"]] + [[1,2]]*5 + [[3,4]]*3 + [[5,6]]*5
             + [[0,1]] + [[-1,-1]]),
}

def carr(name, data):
    return (f"static const unsigned char {name}[{len(data)}] = {{"
            + ",".join(map(str, data)) + "};\n")

def gen(prefix, schema, cols, f):
    sm = schema_message(schema)
    m, _ = batch_message(schema, cols)
    msg = fb.Tbl.root(m)
    assert msg.u8(fb.MSG.HEADER_TYPE) == fb.HEADER_BATCH
    rb = msg.union(fb.MSG.HEADER)
    ns, nn = rb.vector(fb.BATCH.NODES)
    bs, nb = rb.vector(fb.BATCH.BUFFERS)
    f.write(carr(f"{prefix}_SCHEMA_META", sm))
    f.write(f"#define {prefix}_SCHEMA_LEN {len(sm)}\n")
    f.write(carr(f"{prefix}_BATCH_TMPL", m))
    f.write(f"#define {prefix}_TMPL_LEN {len(m)}\n")
    f.write(f"#define {prefix}_OFF_BODYLEN {msg.slot_pos(fb.MSG.BODY_LENGTH)}\n")
    f.write(f"#define {prefix}_OFF_RBLEN {rb.slot_pos(fb.BATCH.LENGTH)}\n")
    f.write(f"#define {prefix}_N_NODES {nn}\n#define {prefix}_N_BUFS {nb}\n")
    f.write(f"static const int {prefix}_NODE_OFF[{nn}] = {{"
            + ",".join(str(ns + 16*i) for i in range(nn)) + "};\n")
    f.write(f"static const int {prefix}_BUF_OFF[{nb}] = {{"
            + ",".join(str(bs + 16*i) for i in range(nb)) + "};\n")
    print(f"{prefix}: tmpl={len(m)}B nodes={nn} bufs={nb}")

with open(sys.argv[1] if len(sys.argv) > 1 else "ipc_gen.h", "w") as f:
    f.write("/* generated by quiver/compiler/gen_templates.py */\n")
    f.write("/* opcodes — single source: quiver/opcodes.py */\n")
    for name, val in OPCODES.items():
        f.write(f"#define OP_{name} {val}\n")
    for p, (s, c) in SCHEMAS.items():
        gen(p, s, c, f)
