#!/usr/bin/env python3
"""qvm2 record-emit templates (QREC): the scan record batch qvm2 emits from C and
polars reads vectorized. Sibling of gen_templates.py (same mechanism, separate
header so bvm's ipc_gen.h never churns for qvm2 work)."""
import sys
from quiver.pupyarrow import fb
from quiver.pupyarrow.writer import batch_message, schema_message

SCHEMA = [("name", "large_string"), ("kind", "u8"), ("mode", "i32"),
          ("size", "i64"), ("mtime_ns", "i64"), ("uid", "i32"), ("gid", "i32"),
          ("tid", "i32"), ("final", "u8"), ("phase", "u8")]
COLS = [["a", "bb"], [0, 1], [1, 2], [3, 4], [5, 6], [7, 8], [9, 10],
        [11, 12], [0, 1], [0, 1]]

def carr(name, data):
    return (f"static const unsigned char {name}[{len(data)}] = {{"
            + ",".join(map(str, data)) + "};\n")

with open(sys.argv[1] if len(sys.argv) > 1 else "qvm2_gen.h", "w") as f:
    f.write("/* generated by quiver/compiler/gen_qvm2.py */\n")
    sm = schema_message(SCHEMA)
    m, _ = batch_message(SCHEMA, COLS)
    msg = fb.Tbl.root(m)
    assert msg.u8(fb.MSG.HEADER_TYPE) == fb.HEADER_BATCH
    rb = msg.union(fb.MSG.HEADER)
    ns, nn = rb.vector(fb.BATCH.NODES)
    bs, nb = rb.vector(fb.BATCH.BUFFERS)
    f.write(carr("QREC_SCHEMA_META", sm))
    f.write(f"#define QREC_SCHEMA_LEN {len(sm)}\n")
    f.write(carr("QREC_BATCH_TMPL", m))
    f.write(f"#define QREC_TMPL_LEN {len(m)}\n")
    f.write(f"#define QREC_OFF_BODYLEN {msg.slot_pos(fb.MSG.BODY_LENGTH)}\n")
    f.write(f"#define QREC_OFF_RBLEN {rb.slot_pos(fb.BATCH.LENGTH)}\n")
    f.write(f"#define QREC_N_NODES {nn}\n#define QREC_N_BUFS {nb}\n")
    f.write(f"static const int QREC_NODE_OFF[{nn}] = {{"
            + ",".join(str(ns + 16 * i) for i in range(nn)) + "};\n")
    f.write(f"static const int QREC_BUF_OFF[{nb}] = {{"
            + ",".join(str(bs + 16 * i) for i in range(nb)) + "};\n")
    print(f"QREC: tmpl={len(m)}B nodes={nn} bufs={nb}")
