#!/usr/bin/env python3
"""Schema compiler: pupyarrow writes the reference messages and locates
the patch slots in its own bytes. Zero dependencies (numpy only).
pyarrow's role is confined to the test suite: it must read everything
the C executor emits from these templates."""
import sys

from quiver.pupyarrow import fb
from quiver.pupyarrow.writer import batch_message, schema_message

SCHEMAS = {
    "COMP": ([("user_data","u64"),("res","i32"),("read_size","i64"),
              ("cksum","u64"),("etag","large_binary"),("parts","i32")],
             [[1,2],[0,-5],[10,20],[3,4],[b"aa",b"bb"],[0,2]]),
    "STAT": ([("path","large_string"),("size","i64"),("blocks","i64"),
              ("mtime_ns","i64"),("atime_ns","i64"),("ctime_ns","i64"),
              ("ino","u64"),("parent_ino","u64"),("dev","u64"),
              ("mode","i32"),("uid","i32"),("gid","i32"),("nlink","i32"),
              ("depth","i32"),("is_dir","u8")],
             [["a","bb"]] + [[1,2]]*5 + [[3,4]]*3 + [[5,6]]*5 + [[0,1]]),
}

def carr(name, data):
    return (f"static const unsigned char {name}[{len(data)}] = {{"
            + ",".join(map(str, data)) + "};\n")

def gen(prefix, schema, cols, f):
    sm = schema_message(schema)
    m, _ = batch_message(schema, cols)
    msg = fb.Tbl.root(m)
    assert msg.u8(fb.MSG.HEADER_TYPE) == fb.HEADER_BATCH
    rb = msg.union(fb.MSG.HEADER)
    ns, nn = rb.vector(fb.BATCH.NODES)
    bs, nb = rb.vector(fb.BATCH.BUFFERS)
    f.write(carr(f"{prefix}_SCHEMA_META", sm))
    f.write(f"#define {prefix}_SCHEMA_LEN {len(sm)}\n")
    f.write(carr(f"{prefix}_BATCH_TMPL", m))
    f.write(f"#define {prefix}_TMPL_LEN {len(m)}\n")
    f.write(f"#define {prefix}_OFF_BODYLEN {msg.slot_pos(fb.MSG.BODY_LENGTH)}\n")
    f.write(f"#define {prefix}_OFF_RBLEN {rb.slot_pos(fb.BATCH.LENGTH)}\n")
    f.write(f"#define {prefix}_N_NODES {nn}\n#define {prefix}_N_BUFS {nb}\n")
    f.write(f"static const int {prefix}_NODE_OFF[{nn}] = {{"
            + ",".join(str(ns + 16*i) for i in range(nn)) + "};\n")
    f.write(f"static const int {prefix}_BUF_OFF[{nb}] = {{"
            + ",".join(str(bs + 16*i) for i in range(nb)) + "};\n")
    print(f"{prefix}: tmpl={len(m)}B nodes={nn} bufs={nb}")

with open(sys.argv[1] if len(sys.argv) > 1 else "ipc_gen.h", "w") as f:
    f.write("/* generated by quiver/compiler/gen_templates.py */\n")
    for p, (s, c) in SCHEMAS.items():
        gen(p, s, c, f)
